logging:
  level:
    ROOT: INFO
    com.dxc.application: INFO
    io.github.jhipster: INFO
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    contexts: prod
  mail:
    host: localhost
    port: 25
    username: null
    password: null
  thymeleaf:
    cache: true
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    url: ''
    username: ''
    password: ''
server:
  port: 8280
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
jhipster:
  http:
    version: V_1_1
    cache:
      timeToLiveInDays: 1461
  security:
    authentication:
      jwt:
        base64-secret: Y2YyN2E2YjM2ZjQ3ZTJlYzg1ZGZiYzhhMDYxOGI2N2Q0ZDcyOTc5NDkxOTE2YTE3YWY1YWU2N2UzMjU1MTgxMmE5ZGYyN2E5MDg3YzE5MGMyZTg5YTJmNjNjMWNkNDE3ODQ5YmQ4NjE0YWE2MjdhNGI3NGRlZmNhZjVlNjZiYzY=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    from: flightservice@localhost
    base-url: http://my-server-url-to-change
  metrics:
    jmx:
      enabled: true
    prometheus:
      enabled: false
    logs:
      enabled: false
      report-frequency: 60
  logging:
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
